#!python3

import sys

import qtpy.QtWidgets as QtWidgets

from doc_explorer.views.main_view import MainView


def main():
    app = QtWidgets.QApplication(sys.argv)
    main_window = MainView(None)
    main_window.show()
    app.exec()


if __name__ == "__main__":
    main()
